a/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from b.admin import pas


urlpatterns = [
    path('admin/', admin.site.urls),
    path('PASTOR-SAMUEL-AJAYI/', pas.urls),
    path('', include('b.urls')),

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

b/urls.py
from django.urls import path
from . import views



app_name = 'b'


urlpatterns = [
    path('', views.Home, name='home'),
    path('UPLOADS/', views.upload, name='videos'),
    path("contact/", views.contact, name="contact"),

    path('welcome', views.Pastor_desk, name='pastor'),

    path('JOIN-ME-IN-PRAYER/', views.PrayerView, name='pray'),
    path('Biblical-COUNSELling', views.Counselling, name='counsel'),
    path('ABOUT-US/', views.About, name='about'),

    path('BREAKTHROUGH-TIME/', views.Testy, name='testimony'),


    path('PRAYER-MINISTRY/', views.prayerforce, name='prayerforce'),

    path('PROPHETIC-FOCUS/', views.Monthly, name='yt'),


    path('PREACHINGS/', views.service, name='sunday'),
    path('WORD-OF-FAITH/', views.all_message, name='messages'), # messages or sms
    path('MESSAGE<int:id>', views.MDetail, name='detail'),
    path('all-category', views.all_category, name='all-category'),
    path('category<int:id>', views.category, name='category'),

]

b/forms.py
from django import forms
from .models import Invite, Bookshop, Choir, Book
# from .models import Book, Topic,  Tropic,  Contact, YafContact
from .models import Praye

CALL_CHOICES = (
        ( 'Yes', 'Yes'),
        ( 'No','No'),
)
PRAYER_OPTION = (
        ( 'Myself','Myself'),
        ('Spouse', 'Spouse'),
        ('Child', 'Child'),
        ('Friend', 'Friend'),
        ('Sibling', 'Siblings')
)

class PrayerForm(forms.Form):
    full_name = forms.CharField()
    residential = forms.CharField()
    email = forms.EmailField()
    phone = forms.IntegerField()
    church = forms.CharField()
    city = forms.CharField()
    call = forms.ChoiceField(widget=forms.RadioSelect(),choices=CALL_CHOICES)
    pray_for = forms.ChoiceField(widget=forms.RadioSelect(),choices=PRAYER_OPTION)
    prayer  = forms.CharField()


BOOK_OPTION = (
    ('', '..CHOOSE..'),
    ( 'A', 'Anointing for Exploits' ),
    ('B', ' Born to Win'),
    ('C' ,'Conquering Controlling Powers'),
    ('D' , 'The Riches of Redemption '),
    ('E' ,'Possessing Your Possession' ),
    ('F', 'All you Need to Have Your Needs Met'),
    ('G' , 'In Pursuit of Vision'),
    ('H', 'Understanding Divine Direction'),
    ('I' ,'Understanding Vision'),
    ('J', 'Following God’s Plan for your life'),
    ('K', 'How to be led by the Spirit'),
    ('L', 'Breaking the Curses of Life'),
    ('M', 'Pillars of Destiny'),
    ('N', 'Commanding the Supernatural'),
    ('O', 'Keys to Divine Health'),
    ('P', 'Pillars of Destiny'),
    ('Q', 'Ruling Your World'),
    ('R', 'Satan Get Lost'),
    ('S', 'Signs & Wonders Today'),
    ('T', 'The Blood Triumph'),
    ('U', 'The Healing Balm'),
    ('V', 'The Force of Freedom')

)
class BookshopForm(forms.Form):
    buyer_name = forms.CharField(max_length=155)
    mailing_address = forms.CharField(max_length=999)
    email = forms.EmailField()
    book = forms.ChoiceField(choices=BOOK_OPTION, label='Which Book Do you want?')
    copies = forms.IntegerField()
    phone = forms.CharField(max_length=55)
    message = forms.CharField(widget=forms.Textarea)



class InviteForm(forms.ModelForm):
    class Meta:
        model = Invite
        fields = "__all__"

class choirForm(forms.ModelForm):
    class Meta:
        model = Choir
        fields = "__all__"

    # ('The Miracle Meal', 'The Miracle Meal'),
    # ('The Unlimited Power of Faith', 'The Unlimited Power of Faith'),
    # ('Towards Mental Exploits', 'Towards Mental Exploits'),
    # ('Understanding Divine Direction', 'Understanding Divine Direction'),
    # ('Understanding Financial Prosperity', 'Understanding Financial Prosperity'),
    # ('Understanding the Power of Praise', 'Understanding the Power of Praise'),
    # ('Walking in the Miraculous', 'Walking in the Miraculous'),
    # ('Walking in the Newness of Life', 'Walking in the Newness of Life'),
    # ('Winning Prayer', 'Winning Prayer'),
    # ('You Shall Not Be Barren', 'You Shall Not Be Barren')



    # Full_name = forms.CharField(label='',widget=forms.TextInput(attrs={'class': 'frm_txt_fld', 'placeholder':'Your Full Name'}))
    # class Meta:
    #     model = Prayer
    #     fields = ('full_name', 'residential', 'email', 'phone', 'church', 'city' )




# class BookForm(forms.ModelForm):
#     class Meta:
#         model = Book
#         fields = ('title', 'author', 'pdf')
#
#
#
# class TopicForm(forms.ModelForm):
#     class Meta:
#         model = Topic
#         fields = ['text']
#         labels = {'text': ''}
#
#
# class TropicForm(forms.ModelForm):
#     class Meta:
#         model = Tropic
#         fields = ['text']
#         labels = {'text': ''}
#
#
# class ContactForm(forms.ModelForm):
#     class Meta:
#         model = Contact
#         fields = "__all__"
#
# class YafContactForm(forms.ModelForm):
#     class Meta:
#         model = YafContact
#         fields = "__all__"

b/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from .forms import PrayerForm, BookshopForm, choirForm
from django.views.generic import ListView, View
from .models import Praye, Counsel, Invite, Ivpg, Testimony, WOFBI, Bookshop, PDF, Choir, Security, Decoration, CHILDREN,\
    PF, HOSPITALITY, PROPHET_FOCUS, BOOKS_of_the_Months, Recommended_Books, WSF, SPIRITUAL, Recommended_Books_Time,\
    TECHNICAL, USHERING, Services, Category,  Video, SANCTUARY, TRANSPORTATION, HARVESTER, HEALTH_WORKERS, DRAMA,\
    ChoirPage1, ChoirPage2, HomeCarousel, ChoirSong, CA, Contact, Pastor_Desk, Welcome_Speech
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages








#
def About(request):
    return render(request, 'b/aboutus.html')






def service(request):
    # first_sms = Services.objects.first()
    side_sms = Services.objects.all()
    three_category = Category.objects.all()
    context = {
        # 'first_sms' : first_sms,
        'side_sms' : side_sms,
        'three_category' : three_category
    }
    return  render(request, 'b/test.html', context)

def all_message(request):
    all_sms = Services.objects.all()
    context = {
        'all_sms': all_sms
    }
    return render(request, 'b/3.html', context)

def MDetail(request, id):
    sms = Services.objects.get(pk=id)


    context = {
        'sms': sms,

    }
    return render(request, 'b/2.html', context)

def all_category(request):
    cats = Category.objects.all()
    context = {
        'cats' : cats,
    }
    return render(request, 'b/a.html', context)

def category(request, id):
    category = Category.objects.get(id=id)
    sms = Services.objects.filter(category=category)
    context = {
        'all_news': sms,
        'category': category,
    }
    return render(request, 'b/b.html', context)



def cool(request):
    return render(request, 'b/ade.html')




def Home(request):
    img = HomeCarousel.objects.all()
    ws = Welcome_Speech.objects.all()

    context = {
        'img':img,
        'ws':ws
    }
    return render(request, 'b/d.html', context)




def bfc(request):
    return render(request, 'b/bfc.html')




def Monthly(request):
    focus = PROPHET_FOCUS.objects.all()

    book = BOOKS_of_the_Months.objects.all()
    context = {
        'focus' : focus,

        'book' : book,
    }
    return render(request, 'b/focus.html', context)


def prayerforce(request):
    pf = PF.objects.all()
    context = {
        'pf':pf
    }
    return render(request, 'b/p_force.html', context)



#
def Pastor_desk(request):
    desk = Pastor_Desk.objects.all()
    all_sms = Services.objects.all()
    context = {
        'desk': desk,
        'all_sms': all_sms
    }
    return render(request, 'b/pastors_desk.html', context)




def PrayerView(request):
    if request.method=='POST':
        full_name = request.POST.get('full_name', '')
        residential = request.POST.get('residential', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        church = request.POST.get('church', '')
        city = request.POST.get('city', '')
        call = request.POST.get('call', '')
        pray_for = request.POST.get('pray_for', '')
        prayer = request.POST.get('prayer', '')

        p = Praye(
            full_name=full_name,
            residential=residential,
            email=email,
            phone=phone,
            church=church,
            city=city,
            call=call,
            pray_for=pray_for,
            prayer=prayer
        )
        p.save()
        return redirect('b:this-year')
    else:
        return render(request, 'b/request.html')




def Counselling(request):
    if request.method=='POST':
        full_name = request.POST.get('full_name', '')
        residential = request.POST.get('residential', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        church = request.POST.get('church', '')
        city = request.POST.get('city', '')
        call = request.POST.get('call', '')
        counsel = request.POST.get('counsel', '')
        message = request.POST.get('message', '')

        c = Counsel (
                full_name=full_name,
                residential=residential,
                email=email,
                phone=phone,
                church=church,
                city=city,
                call=call,
                counsel=counsel,
                message=message
            )
        c.save()
        return redirect('b:home')

    return render(request, 'b/counselling.html')



def About(request):
    return render(request, 'b/aboutus.html')



def upload(request):
    videos = Video.objects.all()
    paginator = Paginator(videos, 4)
    page = request.GET.get('page')

    try:
        videos = paginator.page(page)

    except PageNotAnInteger:
        videos = paginator.page(1)

    except EmptyPage:
        test = paginator.page(paginator.num_pages)
    context = {
        'videos': videos,
        'page': page
    }
    return render(request, 'b/upload.html', context)

def Testy(request):
    test = Testimony.objects.all()
    paginator = Paginator(test, 2)
    page = request.GET.get('page')

    try:
        test = paginator.page(page)

    except PageNotAnInteger:
        test = paginator.page(1)

    except EmptyPage:
        test = paginator.page(paginator.num_pages)
    context = {
        'test': test,
        'page': page
    }
    return render(request, 'b/testimonies.html', context)



def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        message = request.POST.get('message', '')

        c = Contact(name=name, email=email, message=message)
        c.save()
        # return render(request, 'b/cont.html', {
        #     'name': name,
        #     'email': email,
        #     'navbar': 'cont'
        # })
        return render(request, 'b/cont.html', {
            'name': name,
            'email': email,
            'navbar': 'cont'
        })
    context = {

        'navbar': 'cont'
    }

    return render(request, 'b/cont.html', context)



def gal(request):
    return render(request, 'b/img.html')




#
#
#
# def blog_view(request):
#     posts = Post.objects.all()
#     return render(request, 'b/archies.html', {'posts': posts })
#
# def detail_view(request, id):
#     post = get_object_or_404(Post, id=id)
#     photos = PostImage.objects.filter(post=post)
#     return render(request, 'b/og.html', {
#         'post': post,
#         'photos': photos
#     })
#
# def upload(request):
#     videos = Video.objects.all()
#     return render(request, 'b/upload.html', {
#         'videos': videos
#     })
#
# def services(request):
#     return render(request, 'b/sss.html', {})
#
#
# def wsf(request):
#     books = Book.objects.all()
#     return render(request,'b/wsf_list.html', {
#         'books': books
#     })
#
# def get(self, *args, **kwargs):
    #     form = PrayerForm
    #     context = {
    #         'form':form
    #     }
    #     return render(self.request, 'b/request.html', context)
    #
    # def post(self, *args, **kwargs):
    #     form = PrayerForm(self.request.POST or None)
    #     if form.is_valid():
    #         full_name = form.cleaned_data.get('full_name')
    #         residential = form.cleaned_data.get('residential')
    #         email = form.cleaned_data.get('email')
    #         phone = form.cleaned_data.get('phone')
    #         church = form.cleaned_data.get('church')
    #         city = form.cleaned_data.get('city')
    #         call = form.cleaned_data.get('call')
    #         pray_for = form.cleaned_data.get('pray_for')
    #         prayer = form.cleaned_data.get('prayer')
    #
    #         prayer_request = Prayer (
    #             full_name=full_name,
    #             residential=residential,
    #             email=email,
    #             phone=phone,
    #             church=church,
    #             city=city,
    #             call=call,
    #             pray_for=pray_for,
    #             prayer=prayer
    #         )
    #         prayer_request.save()
    #         print(form.cleaned_data)
    #         return redirect('b:home')
    #     else:
    #         print('form invalid')
    #         return redirect('b:this-year')
#
#
# def shop(request):
#     bookshops = Bookshop.objects.all()
#     return render(request,'b/book_list.html', {
#         'bookshops': bookshops
#     })
#
#
# def contact_form(request):
#     if request.method == 'POST':
#         name = request.POST.get('name', '')
#         email = request.POST.get('email', '')
#         phone = request.POST.get('phone', '')
#         message =  request.POST.get('message', '')
#         contact_form = Contact(name=name, email=email, phone=phone, message=message)
#         contact_form.save()
#         return render(request, 'b/back.html', {'name': name })
#     else:
#         return render(request, 'b/back.html', {})
#
# def yafcontact(request):
#     if request.method == 'POST':
#         email_a = request.POST.get('email')
#         name_b = request.POST.get('name')
#         subject_c = request.POST.get('subject')
#         message_d = request.POST.get('message')
#
#         d = YafContact(email=email_a, name=name_b, subject=subject_c, message=message_d)
#         d.save()
#         return render(request, 'b/alayo.html', {})
#     else:
#         return render(request, 'b/alayo.html')
#
#
# def studio(request):
#     return render(request, 'b/nice.html')
#
#
#
# def topics(request):
#     topics = Topic.objects.order_by('date_added')
#     context = {'topics': topics}
#     return render(request, 'b/topics.html', context)
#
#
# def topic(request, topic_id):
#     topic = Topic.objects.get(id=topic_id)
#     entries = topic.entry_set.order_by('-date_added')

b/templates/b/a.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row main-content">
  <div class="large-12 columns">
    <h3><b style="color:#fff">ALL CATEGORY</b></h3>
    <div class="row">
        {% for cat in cats %}
        <div class="card mb-3 shadow">
            <img src="/media/{{cat.category_image}}" alt="{{cat.title}}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{cat.title}}</h5>
                <p class="card-text"><a href="{% url 'b:category' cat.id %}" class="btn btn-success col-12">VIEW</a></p>
            </div>
        </div>
       {% endfor %}
    </div>
  </div>
</div>






{% endblock content %}

b/templates/b/akorin.html
 {% extends 'base.html' %}
{% load static %}

{% block content %}

<title> MUSIC MINISTRY | Winners Chapel International - Total Garden | winnerschapeltg.org</title>




 <div class="row showcase">

     <div class="large-8 columns" style="height:532px;">
       <div style= class="post_img">
            <div class="orbit-container">
                <!-- Orbit Container -->
                <ul data-orbit="" class="orbit-slides-container ">
                    {% for x in car %}
                    <li class="active">
                        <img src="{{ x.img.url }}">
                    </li>
                    {% endfor %}

                </ul>
            </div>
       </div>
     </div>

   <br>

     <div class="large-4 columns">

       <div class="post_img">

         <div class="orbit-container"><!-- Orbit Container -->
              <ul data-orbit="" class="orbit-slides-container">
                {% for x in card %}
                  <li class="active">
                      <img src="{{ x.img.url }}">
                  </li>
                {% endfor %}
              </ul>
         </div>

         <!-- End Orbit Container -->
       </div>

       <div class="large-12 columns" style="background-color: gold">
         <a href="{% url 'b:songs' %}"><h5 >Download Our Songs Here</h5></a>

       </div>
     </div>
 </div>
 <br><br>
<div class="row main-content"><!-- Main Content -->

  <div class="large-12 columns">
    <div class="row band3"><!-- Row -->
      <div class="large-7 columns">
                <h3>Choir Application Form</h3>
        <form method="POST" action="#"  ">
          {% csrf_token %}
          <fieldset>
            <legend>Kingdom Service Application Form!</legend>

            <div id="status"></div>
            <div class="contact_form">
              <div class="row">
                <div class="small-4 columns">
                  <label style="color:gold;">NAME</label>
                  <input type="text" size="30" class="frm_txt_fld"   placeholder="Your Full Name" name="full_name"/>
                  <br />
                </div>
                <div class="small-4 columns">
                  <label style="color:gold;">ADDRESS</label>
                  <input type="text" size="30" class="frm_txt_fld"   placeholder="Your Residential Address" name="residence"/>
                  <br />
                </div>
                <div class="small-4 columns">
                  <label style="color:gold;">EMAIL</label>
                  <input type="email" size="30" class="frm_txt_fld"  placeholder="Your Email" name="email"/>
                  <br />
                </div>
                <div class="small-4 columns">
                  <label style="color:gold;">PHONE</label>
                  <input type="text" size="15" class="frm_txt_fld"  placeholder="Phone No (999-999-9999)"  name="phone"/>
                  <br />
                </div>
                <div class="small-4 columns">
                  <label style="color:gold;">CITY</label>
                  <input name="city" type="text" class="frm_txt_fld" placeholder="Your City" size="30"/>
                  <br />
                </div>
                <div class="small-4 columns">
                  <label style="color:gold;">ARE U BORN AGAIN?</label>
<!--                  <input name="born_again" type="text" class="frm_txt_fld"  placeholder="Are you Born Again?" size="30"/>-->
                  <input type="radio"  name="born_again" value="Yes"/>
                  Yes  &nbsp;
                  <input type="radio" name="born_again" value="No"/>
                  No &nbsp;
                  <br /><br /><br /><br />
                </div>
                <div class="small-4 columns">
                  <label style="color:gold;">DATE YOU JOINED THIS CHURCH</label>
                  <input name="church" type="date"  class="frm_txt_fld" value="" placeholder="Date I joined this Church"  size="30"/>
                  <br />
                </div>
                <div class="small-4 columns">
                  <label style="color:gold;">DATE OF NEW BIRTH</label>
                  <input name="date_of_new_birth" id="id_date_of_new_birth" type="date" class="frm_txt_fld" value="" placeholder="Date of New Birth"  size="30"/>
                  <br />
                </div>
                <div class="small-4 columns">
                  <label style="color:gold;">Musical Instrument You can play?</label>
                  <input name="instrument" type="text" class="frm_txt_fld" placeholder=" Instrument do you play? "  size="30"/>
                  <br />
                </div>
                <br/>
                <br/>
                <br/>
                <br/>
                <div align="justify" class="small-12 columns"><b style="color:#FFF;">Have you Attended Foundation Class?</b> <font style="color:#FFF; padding-left:5%;">
                  <input type="radio"  name="foundation_class" value="Yes"/>
                  Yes  &nbsp;
                  <input type="radio" name="foundation_class" value="No"/>
                  No &nbsp;

                  </font>
                </div>
                <br/>
                <div align="justify" class="small-12 columns"><b style="color:#FFF;">What Part do you Sing?</b> <font style="color:#FFF; padding-left:5%;">
                  <input type="radio" name="part_sing" value="Soprano"/>
                  Soprano  &nbsp;
                  <input type="radio" name="part_sing" value="Alto"/>
                  Alto &nbsp;
                  <input type="radio" name="part_sing" value="Tenor"/>
                  Tenor &nbsp;
                  <input type="radio" name="part_sing" value="No Idea" />
                  I have no idea! &nbsp;
                  </font>
                </div>
                <br/>
                <div align="justify" class="small-12 columns"><b style="color:#FFF;">What is your Marital Status?</b><font style="color:#FFF; padding-left:5%;">
                  <input type="radio" name="marital_status" value="MARRIED"  />
                  Married  &nbsp;
                  <input type="radio" name="marital_status" value="SINGLE"/>
                  Single &nbsp;
                  <input type="radio" name="marital_status" value="WIDOWED"/>
                  Widowed &nbsp;
                  <input type="radio" name="marital_status" value="SEPARATED"/>
                  Separated &nbsp;
                  <input type="radio" name="marital_status" value="DIVORCED"/>
                  Divorced
                  </font>
                </div>
                <br/>
                <div class="small-12 columns" style="padding-top:5%;">
                  <textarea cols="7" rows="7"  placeholder="Why I want to join the Choir" name="message"></textarea>
                  <br />
                </div>
                <div class="small-12 columns">
                  <input type="submit" class="button success radius medium" value="Send message" name="send" id="send" />
                 <p align="justify" class="fontsforweb_fontid_9785" style="font-size: 13px;">By pressing the <b style="color:red;">Send message Button</b>,
                   you are signing a digital signature, indicating that you are willing to engage yourself in voluntary kingdom service
                   in Winners Chapel International, Total Garden Ibadan, Nigeria, and all Information given are true and verifiable. </p>
                </div>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
      <div class="large-5 columns">
        <h3 align="center">Are You Hiding?   <br/>...join the team!!!</h3>
        <p><i style="font-family:times new roman; font-size:16px; color:#E9EF0D;">Sing unto God a new song; play skilfully, and shout for joy - Psalm 33:3</i>
        <p align="justify" class="fontsforweb_fontid_9785" style="font-size: 13px;"> The Music Ministry of this great asssembly is made up of God fearing men and women, who are talented music ministers and are committed to the work of God in music.<br/>
          They minister in praise, worship and special songs that bring down the glory of God through during our services.<br/>
          <br/>
          They usher the entire congregation into the awesome presence of God and today, by the grace of God, they are a force to reckon with.<br/>
          <br/>
          As the choir leads the congregation into the high praises of God and ultimately His presence, God Himself comes down with His blessings (Psalm 22:3).<br/>
          <br/>
          To belong to this group, experience in singing and skill to play instruments will be an added advantage <b>Your long awaited turn-around and change of story has come!</b></p>
        <br/>
        <div class="contact-details" style="font-family:gothic;">
          <p align="justify" class="fontsforweb_fontid_9785"><span><i class="icon-home"></i></span>Address: KM9, Queen Elizabeth Way, Total Garden, Ibadan, Nigeria </p>
          <p align="justify" class="fontsforweb_fontid_9785"><span><i class="icon-phone"></i></span>Phone: (234) 813-123-4567</p>
          <p align="justify" class="fontsforweb_fontid_9785"><span><i class="icon-envelope"></i></span>E-mail: lfcchoir@gmail.com</p>
        </div>
        <br />
        <ul class="inline-list" style="padding-left:40px; font-family:gothic;">
          <li><a class="smallipopBlue" href="#" title="Facebook"><i class="icon-facebook-sign icon-2x"></i></a></li>
          <li><a class="smallipopBlue" href="#" title="Twitter"><i class="icon-twitter-sign icon-2x"></i></a></li>
          <li><a class="smallipopBlue" href="#" title="Google+"><i class="icon-google-plus-sign icon-2x"></i></a></li>
          <li><a class="smallipopBlue" href="#" title="Linkedin"><i class="icon-linkedin-sign icon-2x"></i></a></li>
          <li><a class="smallipopBlue" href="#" title="Pinterest"><i class="icon-pinterest-sign icon-2x"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

  </div>
</div>



 {% endblock content %}

b/templates/b/home.html
{% extends 'base.html' %}


{% load static %}
{% block content %}



{% block unit %}
    {% include 'b/pillars.html' %}
{% endblock unit %}


{% endblock content %}

b/templates/b/page.html
<div class="">


              <span class="">
              {% if page.has_previous %}
              <a href="?page={{ page.previous_page_number }}">Previous</a>
              {% endif %}

              <span class="">
              Page {{ page.number }} of {{ page.paginator.num_pages }}.
              </span>

              {% if page.has_next %}
              <a href="?page={{ page.next_page_number }}">Next</a>
              {% endif %}
              </span>
    <br>
    <br>
    <br>

</div>

b/templates/b/testimonies.html
{% extends 'base.html' %}


{% load static %}
{% block content %}
<title>Testimonies | Winners Chapel International - Total Garden | winnerschapeltg.org</title>

<div class="row">
  <div class="large-12 columns main-content-top">
    <!-- Row -->
    <div class="row">
      <div class="large-6 columns">
        <h2>Signs &amp; Wonders Today</h2>
      </div>
      <div class="large-6 columns">
        <ul class="breadcrumbs right">
          <li><a href="/">Home</a></li>
          <li class="current"><a href="#">Testimonies</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row band3">
  <h4 align="center"><strong>Acts Of a Mighty God at Winners Chapel International, Total Garden, Ibadan, Nigeria </strong></h4>
    <p style="font-size: 13px; color:gold; margin-left:6px;">Individually and corporately, God has been Good to us. With humbling testimonies of outstanding feats, divine visitations
        and deliverance from destruction, no one can deny that God's presence is lavishly present in this assembly; and that the Liberation Mandate is truly in action at
        Winners Chapel International, Total Garden, Ibadan, Nigeria.<br/>
    Below are a few of our outstanding testimonies...
    </p>
</div>

<div class="row main-content focuscontent">

<!-- Row -->
      {% for x in test %}
    <div style="padding:10px;">
      <div class="large-6 columns">
        <article class="post">
          <div class="post_img"> <img src="/media/{{x.t_img}}" alt="testifier">
            <ul class="meta">
            <li class="calendar"> {{x.t_month}} {{x.t_day}}, {{x.t_year}}</li>
              <li class="comments">{{x.t_name}}.</li>
            </ul>
          </div>
          <h3 align="center"><a href="#"> <strong>{{x.t_title}}.</strong></a></h3>
          <p class="post_text">{{x.t_body| safe}}</p></b><br/><br/><br/>
        </article>
      </div>

     {% endfor %}
    </div>
        <br><br><br>
    <div style="background-color: #000" >
        {% include 'b/page.html' with page=test %}
    </div>
</div>
<div align="justify" style="color:gold; background-color:green;">
    <strong >Do you have a testimony?</strong> <a href="mailto:testimonies@winnerschapeltoronto.org?cc=technical@winnerschapeltoronto.org, ani@winnerschapeltoronto.org, info@winnerschapeltoronto.org&bcc=testimonies@winnerschapeltoronto.org&subject=Good%20News"><strong>Email Us</strong></a>
</div>
      <div class="clearfix"></div>





{% endblock content %}